---
version: "2.0"

services:
  web:
    image: djHenryStackz/bassmuffin
    expose:
      - port: 80
        as: 80
        accept:
          - bassmuffin.com
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    dcloud:
       pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    dcloud:
      profile: web
      count: 1
