---
version: "1.0"

services:
  web:
    image: djHenryStackz/bassmuffin
    expose:
      - port: 80
        as: 80
        accept:
          - bassmuffin.com
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 512Mi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1tqx5m8sgdcd0eksm8ru9pfzf4g9l8pffwmat3d"
      pricing:
        web:
          denom: uakt
          amount: 1

deployment:
  web:
    dcloud:
      profile: web
      count: 1
